<a href="https://colab.research.google.com/github/arun-arunisto/OpenCVTutorialAbel/blob/main/NumpyTutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#list - Array
#python list consist space complexity - 8gb - double
#numpy arrays consist less memory

In [2]:
import sys

li = []

sys.getsizeof(li)

56

In [3]:
import numpy as np

sample_array = np.array([])
sys.getsizeof(sample_array)

112

In [4]:
for i in range(100):
  li.append(i)


In [5]:
li

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99]

In [6]:
sys.getsizeof(li)

920

In [7]:
np_array =  np.array(li)

sys.getsizeof(np_array)

912

In [8]:
#creating a basic array
basic_array = np.array([1, 2, 3])
basic_array

array([1, 2, 3])

In [9]:
#creating a 2-D array
twod_array = np.array([[1, 2, 3], [4, 5, 6]])
twod_array

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
#creating a array filled with 0'
zero_array = np.zeros(4)
zero_array

array([0., 0., 0., 0.])

In [11]:
#creating a array filled with one's
ones_array = np.ones(4)
ones_array

array([1., 1., 1., 1.])

In [12]:
#creating an array with empty
empty_array = np.empty(4)
empty_array

array([1., 1., 1., 1.])

In [13]:
range(1, 4)

range(1, 4)

In [14]:
range_array = np.array(range(1, 4))
range_array

array([1, 2, 3])

In [15]:
#concatenating
first_array = np.array([1, 2, 3])
second_array = np.array([4, 5, 6])

np.concatenate((first_array, second_array))

array([1, 2, 3, 4, 5, 6])

In [24]:
#createing a 3d array
three_d_array = np.array([[[1, 2, 3]],
                          [[4, 5, 6]],
                           [[7, 8, 9]],
                           [[10, 11, 12]]])
three_d_array

array([[[ 1,  2,  3]],

       [[ 4,  5,  6]],

       [[ 7,  8,  9]],

       [[10, 11, 12]]])

In [25]:
#finding the dimensions
three_d_array.ndim

3

In [26]:
#finding the shape
three_d_array.shape

(4, 1, 3)

In [27]:
#finding size of the array
three_d_array.size

12

In [28]:
#finding the maximum
three_d_array.max()

12

In [29]:
#finding the minimum value
three_d_array.min()

1

In [30]:
#to find the sum
three_d_array.sum()

78

In [31]:
#creating array with random numbers
rng = np.random.default_rng()
ran = rng.integers(100, size=(1080, 720))

In [32]:
ran

array([[ 2, 38, 52, ..., 60, 38,  1],
       [48, 40, 77, ..., 88, 48, 20],
       [23, 66,  2, ..., 88, 74, 70],
       ...,
       [69, 96, 57, ..., 30, 30,  2],
       [82, 11, 75, ..., 91, 83, 16],
       [49, 52, 52, ...,  4, 86,  5]])

In [33]:
#getting the unique values from an array
uni = np.unique(ran)
uni

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [34]:
#reversing an array
rev = np.flip(uni)
rev

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [35]:
#daving and loading a numpy array
np.save("reverse", rev)

In [36]:
file_ = np.load("reverse.npy")
file_

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])